version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: dhobi-backend
    env_file:
      - ./backend/.env
    ports:
      - "1200:1200"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: dhobi-frontend
    ports:
      - "1100:1100"
    restart: unless-stopped
    depends_on:
      - backend
